apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdf-api
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pdf-api
  template:
    metadata:
      labels:
        app: pdf-api
    spec:
      serviceAccountName: pdf-worker-sa
      containers:
      - name: pdf-api
        image: 086241318869.dkr.ecr.us-east-1.amazonaws.com/projectview-app:6eee80fc4fb2f9f01ca3d5b16f7d0b6f4f36a0c5
        ports:
        - containerPort: 5000
        env:
        - name: SIGNED_QUEUE_URL
          value: "https://sqs.us-east-1.amazonaws.com/086241318869/projectview-dev-signed"
        - name: FREE_QUEUE_URL
          value: "https://sqs.us-east-1.amazonaws.com/086241318869/projectview-dev-free"
        - name: S3_BUCKET
          value: "projectview-dev-pdfs-086241318869"
        - name: API_KEY
          value: "my-secret-api-key-123"
        - name: DB_HOST
          value: "projectview-dev-rds.c8ziggwg07rn.us-east-1.rds.amazonaws.com"
        - name: DB_NAME
          value: "projectview"
        - name: DB_USER
          value: "dbadmin"
        - name: DB_PASSWORD
          value: "j~1|g>q:VVDJ5!_Oz1wgxYHm>Y(t"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: free-worker
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: free-worker
  template:
    metadata:
      labels:
        app: free-worker
    spec:
      serviceAccountName: pdf-worker-sa
      containers:
      - name: free-worker
        image: 086241318869.dkr.ecr.us-east-1.amazonaws.com/projectview-app:6eee80fc4fb2f9f01ca3d5b16f7d0b6f4f36a0c5
        command: ["python", "worker.py"]
        env:
        - name: QUEUE_URL
          value: "https://sqs.us-east-1.amazonaws.com/086241318869/projectview-dev-free"
        - name: QUEUE_TYPE
          value: "free"
        - name: S3_BUCKET
          value: "projectview-dev-pdfs-086241318869"
        - name: DB_HOST
          value: "projectview-dev-rds.c8ziggwg07rn.us-east-1.rds.amazonaws.com"
        - name: DB_NAME
          value: "projectview"
        - name: DB_USER
          value: "dbadmin"
        - name: DB_PASSWORD
          value: "j~1|g>q:VVDJ5!_Oz1wgxYHm>Y(t"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: signed-worker
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: signed-worker
  template:
    metadata:
      labels:
        app: signed-worker
    spec:
      serviceAccountName: pdf-worker-sa
      containers:
      - name: signed-worker
        image: 086241318869.dkr.ecr.us-east-1.amazonaws.com/projectview-app:6eee80fc4fb2f9f01ca3d5b16f7d0b6f4f36a0c5
        command: ["python", "worker.py"]
        env:
        - name: QUEUE_URL
          value: "https://sqs.us-east-1.amazonaws.com/086241318869/projectview-dev-signed"
        - name: QUEUE_TYPE
          value: "signed"
        - name: S3_BUCKET
          value: "projectview-dev-pdfs-086241318869"
        - name: DB_HOST
          value: "projectview-dev-rds.c8ziggwg07rn.us-east-1.rds.amazonaws.com"
        - name: DB_NAME
          value: "projectview"
        - name: DB_USER
          value: "dbadmin"
        - name: DB_PASSWORD
          value: "j~1|g>q:VVDJ5!_Oz1wgxYHm>Y(t"
---
apiVersion: v1
kind: Service
metadata:
  name: pdf-api
  namespace: dev
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  type: LoadBalancer
  selector:
    app: pdf-api
  ports:
  - port: 80
    targetPort: 5000
